(function(global){
  'use strict';
  const labels=[['waterCost','Вода'],['hotWaterCost','Гаряча вода'],['electroCost','Світло'],['gasCost','Газ'],['customCost','Додаткові послуги']];
  const cents=value=>Math.round(Math.max(0,Number(value)||0)*100);
  function build(address,month,paidAmount){
    const records=Array.isArray(address?.records)?address.records:[],record=records.find(item=>item.month===month);if(!record)return null;
    const total=cents(record.total),paid=Math.min(total,cents(paidAmount(record))),balance=Math.max(0,total-paid);
    const [year,period]=String(month).split('-').map(Number),previous=period===1?`${year-1}-12`:`${year}-${String(period-1).padStart(2,'0')}`,prior=records.find(item=>item.month===previous);
    const change=prior&&cents(prior.total)>0?Math.round((total-cents(prior.total))/cents(prior.total)*100):null;
    return{month,total:total/100,paid:paid/100,balance:balance/100,change,previous,services:labels.filter(([key])=>cents(record[key])>0).map(([key,label])=>({label,amount:cents(record[key])/100}))};
  }
  let dialog,api;
  const money=value=>new Intl.NumberFormat('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value)+' ₴';
  const date=month=>new Date(month+'-01T12:00:00').toLocaleDateString('uk-UA',{month:'long',year:'numeric'});
  function close(){if(!dialog)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');}
  function text(summary){return ['Комуналка · підсумок місяця',api.address().name,date(summary.month),`Нараховано: ${money(summary.total)}`,`Сплачено: ${money(summary.paid)}`,`Залишилось: ${money(summary.balance)}`,...summary.services.map(item=>`${item.label}: ${money(item.amount)}`),...(summary.change===null?[]:[`Зміна нарахувань до попереднього місяця: ${summary.change>0?'+':''}${summary.change}%`])].join('\n');}
  function render(){if(!api.valid()){close();return;}const summary=build(api.address(),dialog.querySelector('select').value,api.paid);const content=dialog.querySelector('#monthlySummaryContent');content.replaceChildren();dialog.querySelector('#monthlySummaryCopyStatus').textContent='';if(!summary)return;for(const [label,value] of [['Нараховано',summary.total],['Сплачено',summary.paid],['Залишилось',summary.balance]]){const row=document.createElement('div');row.className='monthly-summary-row';const title=document.createElement('span'),amount=document.createElement('strong');title.textContent=label;amount.textContent=money(value);row.append(title,amount);content.append(row);}if(summary.change!==null){const note=document.createElement('p');note.textContent=`Зміна нарахувань: ${summary.change>0?'+':''}${summary.change}%. Порівняння з попереднім місяцем (${date(summary.previous)}). Різниця може залежати від тарифів і набору послуг.`;note.className='monthly-summary-note';content.append(note);}const preview=dialog.querySelector('#monthlySummaryText');preview.value=text(summary);}
  function open(options){
    api=options;if(!api.valid())return;
    if(!dialog){dialog=document.createElement('dialog');dialog.id='monthlySummaryDialog';dialog.className='action-dialog monthly-summary-dialog';dialog.setAttribute('aria-labelledby','monthlySummaryTitle');dialog.innerHTML='<h2 id="monthlySummaryTitle">Підсумок місяця</h2><p id="monthlySummaryAddress"></p><label for="monthlySummaryMonth">Місяць</label><select id="monthlySummaryMonth"></select><div id="monthlySummaryContent"></div><details><summary>Текст для копіювання</summary><textarea id="monthlySummaryText" rows="8" readonly aria-label="Текст підсумку"></textarea></details><p id="monthlySummaryCopyStatus" role="status"></p><div class="dialog-actions"><button type="button" id="monthlySummaryClose" class="button-secondary">Закрити</button><button type="button" id="monthlySummaryCopy" class="button-primary">Скопіювати підсумок</button></div>';document.body.append(dialog);dialog.querySelector('select').addEventListener('change',render);dialog.querySelector('#monthlySummaryClose').addEventListener('click',close);dialog.querySelector('#monthlySummaryCopy').addEventListener('click',async()=>{if(!api.valid()){close();return;}render();const current=api;try{await navigator.clipboard.writeText(dialog.querySelector('textarea').value);if(current===api&&api.valid())dialog.querySelector('#monthlySummaryCopyStatus').textContent='Підсумок скопійовано ✓';}catch{if(current!==api||!api.valid())return;dialog.querySelector('details').open=true;dialog.querySelector('textarea').focus();dialog.querySelector('textarea').select();dialog.querySelector('#monthlySummaryCopyStatus').textContent='Оберіть «Копіювати» для виділеного тексту.';}});}
    const address=api.address();dialog.querySelector('#monthlySummaryAddress').textContent=address.name;const select=dialog.querySelector('select');select.replaceChildren();const months=[...new Set(address.records.map(record=>record.month))].sort().reverse();for(const month of months){const option=document.createElement('option');option.value=month;option.textContent=date(month);select.append(option);}if(!months.length){api.empty();return;}select.value=months.includes(api.month)?api.month:months[0];render();if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');
  }
  global.KomunalkaMonthlySummary=Object.freeze({build,open,close});
})(globalThis);
