import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const queueSource=await readFile(new URL('../sync-queue.js',import.meta.url),'utf8');
const storeSource=await readFile(new URL('../data-store.js',import.meta.url),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
function setup(){const data=new Map();const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};const context={window:{localStorage:storage},Date,Math,JSON};vm.runInNewContext(queueSource,context);vm.runInNewContext(storeSource,context);return{storage,data,api:context.window.KomunalkaData,queue:context.window.KomunalkaSyncQueue};}
const snapshot=()=>({addresses:[{id:'home',name:'Дім',tariffs:{water:30.38},prefs:{},customServices:[],records:[{id:1,month:'2026-08',total:151.9,waterCost:151.9,wPrev:124,wCur:129,note:'Старий запис',paid:true,customField:{keep:true}}]}],currentAddressId:'home'});
test('legacy backup is byte-for-byte unchanged; accounts and drafts are isolated',()=>{const {storage,api}=setup();const raw=JSON.stringify(snapshot());storage.setItem('komynalka_backup',raw);const a=api.create(storage,'a'),b=api.create(storage,'b');a.initialize(snapshot(),1);b.initialize({addresses:[],currentAddressId:'default'},0);a.saveDraft('home','2026-09',{wCur:'0',paidAmount:'20'});assert.equal(b.draft('home','2026-09'),null);assert.equal(a.draft('other','2026-09'),null);assert.equal(a.draft('home','2026-10'),null);assert.equal(a.draft('home','2026-09').wCur,'0');assert.equal(b.read().local.addresses.length,0);assert.equal(storage.getItem('komynalka_backup'),raw);});
test('new edits during an in-flight save are persisted and sent after the earlier acknowledgement',async()=>{const {storage,api,queue}=setup();const store=api.create(storage,'a');const base=snapshot();store.initialize(base,1);const first=clone(base);first.addresses[0].records[0].note='A';store.stage(first);let release;const gate=new Promise(r=>release=r);const sent=[];const drain=queue.createDrain(store,async state=>{sent.push(state.local.addresses[0].records[0].note);if(sent.length===1)await gate;return{success:true,revision:sent.length+1};});const running=drain();const second=clone(first);second.addresses[0].records[0].note='B';store.stage(second);assert.equal(api.create(storage,'a').read().local.addresses[0].records[0].note,'B');release();await running;assert.deepEqual(sent,['A','B']);assert.equal(store.read().pending,null);assert.equal(store.read().base.addresses[0].records[0].note,'B');});
test('server errors and protected responses retain pending edits',async()=>{for(const response of [{success:false,error:'FAILED'},{success:true,protected:true}]){const {storage,api,queue}=setup();const store=api.create(storage,'a');store.initialize(snapshot(),1);const next=snapshot();next.addresses[0].records[0].note='Offline';store.stage(next);await assert.rejects(queue.createDrain(store,async()=>response)());assert.ok(store.read().pending);assert.equal(store.read().local.addresses[0].records[0].note,'Offline');}});
test('three-way merge preserves independent edits and unknown fields',()=>{const {storage,api}=setup();const store=api.create(storage,'a');const base=snapshot();store.initialize(base,1);const local=clone(base);local.addresses[0].records.push({id:2,month:'2026-09',total:20});store.stage(local);const remote=clone(base);remote.addresses[0].name='Перейменовано';const state=store.initialize(remote,2);assert.equal(state.conflict,null);assert.equal(state.local.addresses[0].records.length,2);assert.equal(state.local.addresses[0].name,'Перейменовано');assert.equal(state.local.addresses[0].records[0].customField.keep,true);assert.ok(state.pending);});
test('same-field conflict preserves both copies and requires explicit durable resolution',()=>{const {storage,api}=setup();const store=api.create(storage,'a');const base=snapshot();store.initialize(base,1);const local=clone(base),remote=clone(base);local.addresses[0].records[0].note='Local';remote.addresses[0].records[0].note='Remote';store.stage(local);const state=store.initialize(remote,2);assert.ok(state.conflict.paths.length);assert.equal(state.local.addresses[0].records[0].note,'Local');store.resolve('remote');assert.equal(store.backup('conflict').local.addresses[0].records[0].note,'Local');assert.equal(store.read().local.addresses[0].records[0].note,'Remote');});
test('failed backup aborts destructive resolution, corrupt envelopes are never reset',()=>{const {storage,api}=setup();const store=api.create(storage,'a');store.initialize(snapshot(),1);const local=snapshot(),remote=snapshot();local.addresses[0].name='L';remote.addresses[0].name='R';store.stage(local);store.initialize(remote,2);const before=storage.getItem(store.key),write=storage.setItem;storage.setItem=()=>{throw new Error('quota');};assert.throws(()=>store.resolve('remote'));assert.equal(storage.getItem(store.key),before);storage.setItem=write;storage.setItem(store.key,'{bad');assert.throws(()=>store.initialize(snapshot(),3));assert.equal(storage.getItem(store.key),'{bad');});
