import {test} from 'node:test';import assert from 'node:assert/strict';import {createECDH,randomBytes} from 'node:crypto';
import {deliverReminders,nextReminderRun,validateSubscription,sendReminder} from '../push-delivery.js';import '../push-client.js';
function keys(){const key=createECDH('prime256v1');key.generateKeys();return{public:key.getPublicKey().toString('base64url'),private:key.getPrivateKey().toString('base64url')};}
const userKeys=keys(),vapid=keys();const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/test-only',keys:{p256dh:userKeys.public,auth:randomBytes(16).toString('base64url')}};
const env={VAPID_PUBLIC_KEY:vapid.public,VAPID_PRIVATE_KEY:vapid.private,VAPID_SUBJECT:'https://example.com'};
function fixture(){const data=new Map([['push',{subscriptions:[{subscription}]}],['account',{value:{addresses:[{id:'a',prefs:{remindersEnabled:true,showWater:true,showElectro:false,showGas:false}}]}}]]);const ctx={storage:{get:async k=>structuredClone(data.get(k)),put:async(k,v)=>{data.set(k,structuredClone(v));},setAlarm:async t=>data.set('alarm',t),deleteAlarm:async()=>data.delete('alarm')}};return{ctx,data};}
test('background delivery is daily, retries errors, and removes expired subscriptions',async()=>{const {ctx,data}=fixture();const now=new Date('2026-09-01T06:00Z');let calls=0;const send=async()=>{calls++;return 201;};await deliverReminders(ctx,env,send,now);await deliverReminders(ctx,env,send,now);assert.equal(calls,1);assert.equal(data.get('push').subscriptions[0].lastDay,'2026-09-01');const f=fixture();await deliverReminders(f.ctx,env,async()=>503,now);assert.equal(f.data.get('push').subscriptions[0].lastDay,undefined);assert.equal(f.data.get('alarm'),+now+1800000);await deliverReminders(f.ctx,env,async()=>410,now);assert.equal(f.data.get('push').subscriptions.length,0);assert.equal(f.data.has('alarm'),false);});
test('disabled, completed, deleted accounts and maintenance never send',async()=>{for(const change of [f=>f.data.get('account').value.addresses[0].prefs.remindersEnabled=false,f=>f.data.get('account').value.addresses[0].prefs.reminderCompletions={water:'2026-09'},f=>f.data.get('account').deleted=true]){const f=fixture();change(f);await deliverReminders(f.ctx,env,async()=>{assert.fail('Unexpected push');},new Date('2026-09-01T06:00Z'));}await deliverReminders(fixture().ctx,{...env,MAINTENANCE_MODE:'read-only'},async()=>assert.fail(),new Date('2026-09-01T06:00Z'));});
test('09:00 Kyiv schedule follows winter, summer and DST transition',()=>{for(const [from,expected] of [['2026-01-10T08:00Z','2026-01-11T07:00:00.000Z'],['2026-09-01T07:00Z','2026-09-02T06:00:00.000Z'],['2026-03-28T08:00Z','2026-03-29T06:00:00.000Z']])assert.equal(new Date(nextReminderRun(+new Date(from))).toISOString(),expected);});
test('subscription validation blocks arbitrary servers and requires real key sizes',()=>{assert.deepEqual(validateSubscription(subscription),{...subscription,expirationTime:null});for(const endpoint of ['http://fcm.googleapis.com/x','https://localhost/x','https://fcm.googleapis.com.attacker.example/x','https://user@fcm.googleapis.com/x'])assert.throws(()=>validateSubscription({...subscription,endpoint}));assert.throws(()=>validateSubscription({...subscription,keys:{p256dh:'bad',auth:'bad'}}));});
test('actual push payload is encrypted with aes128gcm and VAPID; no live delivery occurs',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url,payload)=>{assert.equal(url,subscription.endpoint);const h=new Headers(payload.headers);assert.equal(h.get('Content-Encoding'),'aes128gcm');assert.match(h.get('Authorization'),/^vapid /);assert.equal(payload.redirect,'manual');assert.ok(payload.body.byteLength>=4000);assert.equal(Buffer.from(payload.body).includes(Buffer.from('Private reminder')),false);return new Response('',{status:201});};try{assert.equal(await sendReminder(env,subscription,{body:'Private reminder'}),201);}finally{globalThis.fetch=original;}});
test('permission alone never means subscribed; server rejection is visible and rolls back a new subscription',async()=>{let state,removed=false;const sub={endpoint:subscription.endpoint,toJSON:()=>subscription,unsubscribe:async()=>{removed=true;return true;}};const client=globalThis.KomunalkaPush.create({request:async(action)=>{if(action==='config')return{enabled:true,publicKey:'x'};throw new Error('server failed');},registration:async()=>({pushManager:{getSubscription:async()=>null,subscribe:async()=>sub}}),permission:{current:()=> 'granted',ask:async()=> 'granted'},subscribeOptions:()=>({}),report:value=>{state=value;}});await client.inspect();assert.equal(state,'available');assert.equal(await client.enable(),false);assert.equal(state,'error');assert.equal(removed,true);});
test('permission is requested only by enable and unsubscribe works when the server is offline',async()=>{let requested=0,removed=0,state;const sub={endpoint:subscription.endpoint,toJSON:()=>subscription,unsubscribe:async()=>{removed++;return true;}};const client=globalThis.KomunalkaPush.create({request:async action=>{if(action==='config')return{enabled:true};if(action==='status')return{subscribed:true};throw new Error('offline');},registration:async()=>({pushManager:{getSubscription:async()=>sub}}),permission:{current:()=> 'granted',ask:async()=>{requested++;return'granted';}},subscribeOptions:()=>({}),report:value=>{state=value;}});await client.inspect();assert.equal(state,'enabled');assert.equal(requested,0);assert.equal(await client.disable(),true);assert.equal(removed,1);});
