import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import worker from '../worker.js';
import {environment,legacyAccount} from './helpers.mjs';
const hash=createHash('sha256').update('test-password').digest('hex');
const auth=login=>`Bearer login:${Buffer.from(login).toString('base64')}:${hash}`;
function req(login,body){return new Request('https://test.workers.dev',{method:body?'POST':'GET',headers:{Authorization:auth(login),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
test('existing account read preserves all historical data and raw recovery snapshot',async()=>{const legacy=legacyAccount(hash);const {env,stores}=environment({anna:legacy});const result=await (await worker.fetch(req('anna'),env)).json();assert.equal(result.success,true);assert.equal(result.data.syncProtocol,2);assert.deepEqual(result.data.addresses,legacy.addresses);assert.equal(stores.get('anna').get('legacy-original').raw,JSON.stringify(legacy));assert.equal(stores.get('anna').get('account').revision,1);});
test('two devices cannot overwrite each other; identical retry is idempotent',async()=>{const {env}=environment({anna:legacyAccount(hash)});const cloud=(await(await worker.fetch(req('anna'),env)).json()).data;const body={addresses:cloud.addresses,currentAddressId:'home',baseRevision:1,clientMutationId:'a'};body.addresses[0].records[0].note='First';const results=await Promise.all([worker.fetch(req('anna',body),env),worker.fetch(req('anna',{...body,clientMutationId:'b'}),env)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await worker.fetch(req('anna',body),env)).status,200);const final=(await(await worker.fetch(req('anna'),env)).json()).data;assert.equal(final.revision,2);assert.equal(final.addresses[0].records[0].note,'First');});
test('legacy snapshot writers are rejected, not allowed to erase other-device records',async()=>{const {env}=environment({anna:legacyAccount(hash)});assert.equal((await worker.fetch(req('anna',{addresses:[]}),env)).status,400);const res=await worker.fetch(req('anna',{addresses:legacyAccount(hash).addresses}),env);assert.equal(res.status,409);assert.equal((await res.json()).error,'SYNC_UPGRADE_REQUIRED');});
test('bare UID and view-only share writes are rejected by server',async()=>{const token='a'.repeat(40);const {env}=environment({anna:legacyAccount(hash),'uid:test':'anna',[`share:${token}`]:{login:'anna',addressId:'home'}});const fake=new Request('https://test.workers.dev',{headers:{Authorization:'Bearer uid:test'}});assert.equal((await worker.fetch(fake,env)).status,401);const share=new Request(`https://test.workers.dev?share=${token}`,{method:'POST',body:JSON.stringify({addresses:[]})});assert.equal((await worker.fetch(share,env)).status,403);});
test('accounts require their own credentials; missing admin secret has no default password',async()=>{const {env}=environment({anna:legacyAccount(hash)});const unauthorized=new Request('https://test.workers.dev',{headers:{Authorization:auth('anna').replace(hash,'0'.repeat(64))}});assert.equal((await worker.fetch(unauthorized,env)).status,403);delete env.ADMIN_PASS;assert.equal((await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'admin_login',pass:'admin123'})}),env)).status,503);});
test('admin listing paginates all keys and includes Google-only accounts',async()=>{const seed={anna:legacyAccount(hash),uid_google:{...legacyAccount(hash),pass:undefined}};for(let i=0;i<1001;i++)seed[`rl:${String(i).padStart(4,'0')}`]='1';const {env}=environment(seed);const adminToken=createHash('sha256').update(`${env.ADMIN_PASS}:${Math.floor(Date.now()/3600000)}:k_admin`).digest('hex');const res=await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'admin_stats',adminToken})}),env);assert.deepEqual((await res.json()).users.map(u=>u.login).sort(),['anna','uid_google']);});
test('request body limit applies without Content-Length; CORS is not wildcard',async()=>{const {env}=environment();const large=new Request('https://test.workers.dev',{method:'POST',body:' '.repeat(513*1024)});assert.equal((await worker.fetch(large,env)).status,413);const preflight=await worker.fetch(new Request('https://test.workers.dev',{method:'OPTIONS',headers:{Origin:'https://komynalka.vercel.app'}}),env);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),'https://komynalka.vercel.app');assert.equal((await worker.fetch(new Request('https://test.workers.dev',{headers:{Origin:'https://unknown.example'}}),env)).status,403);});

test('a committed account remains discoverable and exportable when its KV mirror fails',async()=>{
  const {env,values}=environment();const put=env.KV.put;env.KV.put=async(key,value)=>{if(key==='anna')throw new Error('mirror unavailable');return put(key,value);};
  const snapshot=legacyAccount(hash);const response=await worker.fetch(req('anna',{addresses:snapshot.addresses,currentAddressId:'home',baseRevision:0,clientMutationId:'new-account'}),env);assert.equal(response.status,200);assert.equal(values.has('anna'),false);assert.equal((await(await worker.fetch(req('anna'),env)).json()).data.addresses[0].records[0].total,151.9);
  const adminToken=createHash('sha256').update(`${env.ADMIN_PASS}:${Math.floor(Date.now()/3600000)}:k_admin`).digest('hex');const stats=await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'admin_stats',adminToken})}),env);assert.deepEqual((await stats.json()).users.map(u=>u.login),['anna']);
});

test('maintenance blocks writers and paginated backups retain UID and share mappings verbatim',async()=>{
  const mapping='anna',share=JSON.stringify({login:'anna',addressId:'home'});const {env}=environment({anna:legacyAccount(hash),'uid:google':mapping,'share:example':share});env.MAINTENANCE_MODE='read-only';assert.equal((await worker.fetch(req('anna',{addresses:legacyAccount(hash).addresses,baseRevision:1,clientMutationId:'blocked'}),env)).status,503);
  const adminToken=createHash('sha256').update(`${env.ADMIN_PASS}:${Math.floor(Date.now()/3600000)}:k_admin`).digest('hex');const response=await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'admin_backup_page',adminToken})}),env);const backup=await response.json();assert.equal(backup.readOnly,true);assert.equal(backup.entries.find(e=>e.name==='uid:google').value,mapping);assert.equal(backup.entries.find(e=>e.name==='share:example').value,share);
});

test('old share_ links with phone metadata and capitalized account keys keep working',async()=>{
  const legacy=legacyAccount(hash);const token='legacy_link_12345';const {env,values}=environment({Marina:legacy,[`share_${token}`]:{phone:'Marina',addressId:'home'}});
  const login=await worker.fetch(req('marina'),env);assert.equal(login.status,200);assert.equal((await login.json()).data.linkedLogin,'Marina');
  const share=await worker.fetch(new Request(`https://test.workers.dev?share=${token}`),env);assert.equal(share.status,200);assert.equal((await share.json()).data.addresses[0].records[0].total,151.9);assert.equal(values.has('marina'),false);
});
test('opaque old accounts are preserved and flagged; Google and share aliases are not accounts',async()=>{
  const opaque='synthetic-old-opaque-value';const {env,values}=environment({anna:legacyAccount(hash),encrypted:opaque,google_example:'anna',share_old:{phone:'anna',addressId:'home'},_broadcast:{message:'Test'}});
  const adminToken=createHash('sha256').update(`${env.ADMIN_PASS}:${Math.floor(Date.now()/3600000)}:k_admin`).digest('hex');const res=await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'admin_stats',adminToken})}),env);const data=await res.json();assert.deepEqual(data.users.map(u=>u.login),['anna']);assert.equal(data.unrecognizedAccounts,1);assert.equal((await worker.fetch(req('encrypted'),env)).status,503);assert.equal(values.get('encrypted'),opaque);
});
test('push subscriptions are authenticated, schedule an alarm and do not alter account history',async()=>{
  const {createECDH,randomBytes}=await import('node:crypto');const key=createECDH('prime256v1');key.generateKeys();const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/local-test',keys:{p256dh:key.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}};
  const legacy=legacyAccount(hash),{env,stores,values}=environment({anna:legacy});Object.assign(env,{VAPID_PUBLIC_KEY:'public-test',VAPID_PRIVATE_KEY:'private-test',VAPID_SUBJECT:'https://example.com'});
  const config=await(await worker.fetch(new Request('https://test.workers.dev?push-config=1'),env)).json();assert.equal(config.enabled,true);assert.equal(JSON.stringify(config).includes('private-test'),false);
  const subscribedAt=Date.now(),response=await worker.fetch(req('anna',{action:'push_subscribe',subscription}),env);assert.equal(response.status,200);assert.ok(stores.get('anna').get('__alarm')>=subscribedAt&&stores.get('anna').get('__alarm')<=Date.now()+6000);assert.deepEqual(JSON.parse(values.get('anna')),legacy);
  stores.get('anna').set('__alarm',Date.now()+86400000);const status=await(await worker.fetch(req('anna',{action:'push_status',endpoint:subscription.endpoint}),env)).json();assert.equal(status.subscribed,true);assert.ok(status.nextCheckAt<=Date.now()+6000);
  const cloud=(await(await worker.fetch(req('anna'),env)).json()).data;cloud.addresses[0].prefs={...cloud.addresses[0].prefs,remindersEnabled:true,remWaterStart:20,remWaterEnd:25};stores.get('anna').set('__alarm',Date.now()+86400000);assert.equal((await worker.fetch(req('anna',{addresses:cloud.addresses,currentAddressId:'home',baseRevision:cloud.revision,clientMutationId:'reminder-edit'}),env)).status,200);assert.ok(stores.get('anna').get('__alarm')<=Date.now()+6000);
  assert.equal((await worker.fetch(new Request('https://test.workers.dev',{method:'POST',body:JSON.stringify({action:'push_subscribe',subscription})}),env)).status,401);
  await worker.fetch(req('anna',{action:'push_unsubscribe',endpoint:subscription.endpoint}),env);assert.equal(stores.get('anna').has('__alarm'),false);
});
